### PR TITLE
Update babel-istanbul to 0.8.x to fix #4

### LINKED ISSUE #4: Update babel-istanbul to 0.8.x
babel-istanbul < 0.8.x cannot handle exporting default anonymous functions (see code example and stack track below).  This is due to an issue with escodegen that was fixed and released in babel-istanbul 0.8.0.

I can submit a PR with package.json update if needed.

``` javascript
export default function() {}

/*
Module build failed: TypeError: Cannot read property 'name' of undefined
  at CodeGenerator.Expression.ExportSpecifier (/Users/brent/dev/web/node_modules/babel-istanbul-loader/node_modules/escodegen/escodegen.js:2265:54)
  at CodeGenerator.generateExpression (/Users/brent/dev/web/node_modules/babel-istanbul-loader/node_modules/escodegen/escodegen.js:2427:28)
  at /Users/brent/dev/web/node_modules/babel-istanbul-loader/node_modules/escodegen/escodegen.js:1242:46
  at withIndent (/Users/brent/dev/web/node_modules/babel-istanbul-loader/node_modules/escodegen/escodegen.js:582:9)
  at CodeGenerator.Statement.ExportDeclaration (/Users/brent/dev/web/node_modules/babel-istanbul-loader/node_modules/escodegen/escodegen.js:1237:21)
  at CodeGenerator.Statement.ExportNamedDeclaration (/Users/brent/dev/web/node_modules/babel-istanbul-loader/node_modules/escodegen/escodegen.js:1274:25)
  at CodeGenerator.generateStatement (/Users/brent/dev/web/node_modules/babel-istanbul-loader/node_modules/escodegen/escodegen.js:2440:33)
  at CodeGenerator.Statement.Program (/Users/brent/dev/web/node_modules/babel-istanbul-loader/node_modules/escodegen/escodegen.js:1703:43)
  at CodeGenerator.generateStatement (/Users/brent/dev/web/node_modules/babel-istanbul-loader/node_modules/escodegen/escodegen.js:2440:33)
  at generateInternal (/Users/brent/dev/web/node_modules/babel-istanbul-loader/node_modules/escodegen/escodegen.js:2461:28)
  at Object.generate (/Users/brent/dev/web/node_modules/babel-istanbul-loader/node_modules/escodegen/escodegen.js:2529:18)
  at Object.Instrumenter.instrumentASTSync (/Users/brent/dev/web/node_modules/babel-istanbul-loader/node_modules/babel-istanbul/lib/instrumenter.js:562:32)
  at Object.Instrumenter.instrumentSync (/Users/brent/dev/web/node_modules/babel-istanbul-loader/node_modules/babel-istanbul/lib/instrumenter.js:471:25)
  at Object.Instrumenter.instrument (/Users/brent/dev/web/node_modules/babel-istanbul-loader/node_modules/babel-istanbul/lib/instrumenter.js:597:37)
  at Object.module.exports (/Users/brent/dev/web/node_modules/babel-istanbul-loader/index.js:66:18)
*/
```

### PR DESCRIPTION
**Pull request by bmealhouse**

### CODE REVIEW

**Comment by blake-newman** [comment]
@deepsweet 

I noticed that the current version of `babel-istanbul` is `0.11`. Thus making this PR outdated. 

QQ: what is the status of this project, is it still maintained. Or do you recommend moving to another setup.

Please see https://github.com/vuejs-templates/webpack/pull/402

**Comment by bmealhouse** [comment]
@blake-newman 

Yeah, this PR is definitely outdated.  I ended up using [babel-plugin-\_\_coverage\_\_](https://github.com/dtinth/babel-plugin-__coverage__) after doing more research.

Home that helps.

**Comment by deepsweet** [comment]
https://github.com/deepsweet/istanbul-instrumenter-loader

**Comment by blake-newman** [comment]
@deepsweet does that support ES6 though?

**Comment by deepsweet** [comment]
@blake-newman yep, just forgot to update readme. it's ES6 ready using offical new https://github.com/istanbuljs/ stuff.

**Comment by blake-newman** [comment]
Awesome i'll check it out! Cheers

**Pull request closed without merging**
